# Generated by Django 2.2.16 on 2022-02-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_box', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='DrugBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit', models.CharField(choices=[('pieces', 'pieces'), ('ml', 'milliliter'), ('ampoule', 'ampoule'), ('pills', 'pills')], max_length=7, verbose_name='Единица измерения')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_in_box', to='preparations.Box')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_in_box', to='preparations.Drug')),
            ],
            options={
                'verbose_name': 'Лекарство в боксе',
                'verbose_name_plural': 'Лекарства в боксе',
                'ordering': ('drug__name',),
            },
        ),
        migrations.AddField(
            model_name='box',
            name='drugs',
            field=models.ManyToManyField(blank=True, related_name='box', through='preparations.DrugBox', to='preparations.Drug', verbose_name='Препарат'),
        ),
        migrations.AddConstraint(
            model_name='drugbox',
            constraint=models.UniqueConstraint(fields=('box', 'drug', 'unit'), name='unique_drug_in_box'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_author_box'),
        ),
    ]
