# Generated by Django 2.2.16 on 2022-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugbox',
            name='unit',
            field=models.CharField(choices=[('pieces', 'pieces'), ('milliliter', 'ml'), ('ampoule', 'ampoule'), ('pills', 'pills')], max_length=10, verbose_name='Единица измерения'),
        ),
    ]
