# Generated by Django 2.2.16 on 2022-02-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0002_auto_20220205_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugbox',
            name='unit',
            field=models.CharField(choices=[('pieces', 'шт.'), ('milliliter', 'мл.'), ('ampoule', 'ампулы'), ('pills', 'таблетки')], max_length=10, verbose_name='Единица измерения'),
        ),
    ]
